version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
