version: 0.0
os: linux

hooks:
  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
